In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
# clustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
#3d visualization
import plotly as py
import plotly.graph_objs as go
import warnings
warnings.filterwarnings('ignore')

In [15]:
df=pd.read_csv('C:/Users/zhaleh/PhD_Projects/Hierarchy_to_Beat_Perception_Auditory_Visual/results/PreprocessedResults_101participants.csv')
df

Name  AudSD  AudSeq  AudBeat  VisSD  VisSeq  VisBeat  \
0    10059   0.79    0.57     0.53   0.76    0.67     0.53   
1    10579   0.90    0.97     1.00   0.76    0.87     0.90   
2    11127   0.90    0.70     0.37   0.71    0.70     0.53   
3    13536   0.79    0.57     0.50   0.57    0.60     0.23   
4    14152   0.79    0.43     0.93   0.57    0.50     0.23   
..     ...    ...     ...      ...    ...     ...      ...   
96   96210   0.81    0.70     0.73   0.71    0.73     0.53   
97   97732   0.71    0.53     0.87   0.50    0.50     0.30   
98   98019   0.48    0.30     0.43   0.81    0.27     0.40   
99   98166   0.71    0.47     0.20   0.62    0.40     0.27   
100  99608   0.74    0.67     0.83   0.60    0.40     0.30   

     Musician_years of instruction ( >= 5 -> 2 )  Unnamed: 8  \
0                                              2         NaN   
1                                              1         NaN   
2                                              1         NaN   
3                                              1         NaN   
4                                              1         NaN   
..                                           ...         ...   
96                                             1         NaN   
97                                             2         NaN   
98                                             1         NaN   
99                                             1         NaN   
100                                            1         NaN   

     AudSDIntDiff (T)  ...  AudIrregIntDiff (T)  AudIrregIntDiff (F)  \
0                1.81  ...                 2.90                 2.78   
1                1.73  ...                 2.87                 2.10   
2                1.74  ...                 2.90                 2.72   
3                1.78  ...                 2.82                 2.88   
4                1.88  ...                 3.02                 2.71   
..                ...  ...                  ...                  ...   
96               1.88  ...                 2.80                 2.97   
97               1.99  ...                 3.08                 2.59   
98               1.85  ...                 2.74                 2.89   
99               1.88  ...                 2.96                 2.75   
100              1.96  ...                 2.87                 2.80   

     AudRegIntDiff (T)  AudRegIntDiff (F)  VisSDIntDiff (T)  VisSDIntDiff (F)  \
0                 1.75               1.79              1.87              0.89   
1                 1.77               0.00              1.84              0.99   
2                 1.91               1.68              1.99              0.75   
3                 1.67               1.87              1.85              1.36   
4                 1.75               2.00              1.90              1.28   
..                 ...                ...               ...               ...   
96                1.68               2.00              1.85              1.10   
97                1.77               1.75              1.70              1.58   
98                1.77               1.76              1.79              0.99   
99                1.67               1.79              1.95              1.13   
100               1.80               1.60              1.88              1.28   

     VisIrregIntDiff (T)  VisIrregIntDiff (F)  VisRegIntDiff (T)  \
0                   2.90                 2.74               1.75   
1                   2.89                 2.55               1.85   
2                   2.88                 2.77               1.88   
3                   2.92                 2.73               1.86   
4                   2.99                 2.70               1.71   
..                   ...                  ...                ...   
96                  3.05                 2.30               1.81   
97                  2.99                 2.70               1.78   
98                  2.78                 2

In [12]:
# df.describe()

In [13]:
# to check if we have null values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 21 columns):
 #   Column                                       Non-Null Count  Dtype  
---  ------                                       --------------  -----  
 0   Name                                         101 non-null    int64  
 1   AudSD                                        101 non-null    float64
 2   AudSeq                                       101 non-null    float64
 3   AudBeat                                      101 non-null    float64
 4   VisSD                                        101 non-null    float64
 5   VisSeq                                       101 non-null    float64
 6   VisBeat                                      101 non-null    float64
 7   Musician_years of instruction ( >= 5 -> 2 )  101 non-null    int64  
 8   Unnamed: 8                                   0 non-null      float64
 9   AudSDIntDiff (T)                             101 non-null    float64
 10  Au

In [14]:
df.columns

Index(['Name', 'AudSD', 'AudSeq', 'AudBeat', 'VisSD', 'VisSeq', 'VisBeat',
       'Musician_years of instruction ( >= 5 -> 2 )', 'Unnamed: 8',
       'AudSDIntDiff (T)', 'AudSDIntDiff (F)', 'AudIrregIntDiff (T)',
       'AudIrregIntDiff (F)', 'AudRegIntDiff (T)', 'AudRegIntDiff (F)',
       'VisSDIntDiff (T)', 'VisSDIntDiff (F)', 'VisIrregIntDiff (T)',
       'VisIrregIntDiff (F)', 'VisRegIntDiff (T)', 'VisRegIntDiff (F)'],
      dtype='object')

# <span style='background:yellow'> 3 clusters </span>

In [35]:
df=pd.read_csv('C:/Users/zhaleh/PhD_Projects/Hierarchy_to_Beat_Perception_Auditory_Visual/results/PreprocessedResults_101participants.csv')
df2=df[['AudSD','AudSeq','AudBeat']]
df2.head

<bound method NDFrame.head of      AudSD  AudSeq  AudBeat
0     0.79    0.57     0.53
1     0.90    0.97     1.00
2     0.90    0.70     0.37
3     0.79    0.57     0.50
4     0.79    0.43     0.93
..     ...     ...      ...
96    0.81    0.70     0.73
97    0.71    0.53     0.87
98    0.48    0.30     0.43
99    0.71    0.47     0.20
100   0.74    0.67     0.83

[101 rows x 3 columns]>

In [36]:
model2=KMeans(n_clusters=3, init='k-means++',algorithm='elkan',
              max_iter=2000, random_state=25) # random_state=45
model2.fit(df2)

KMeans(algorithm='elkan', max_iter=2000, n_clusters=3, random_state=25)

In [37]:
df2['Cluster']=model2.fit_predict(df2)
df2.head()

AudSD  AudSeq  AudBeat  Cluster
0   0.79    0.57     0.53        2
1   0.90    0.97     1.00        1
2   0.90    0.70     0.37        2
3   0.79    0.57     0.50        2
4   0.79    0.43     0.93        2

In [38]:
labels=model2.labels_
centroids=model2.cluster_centers_
df2['labels']=labels
print(centroids)

[[0.70205882 0.38705882 0.37147059]
 [0.79285714 0.76392857 0.77892857]
 [0.75666667 0.52692308 0.59333333]]


In [39]:
df2['labels']=labels
trace=go.Scatter3d(x=df2['AudSD'], y=df1['AudSeq'], z=df2['AudBeat'], 
                   mode='markers', 
                   marker=dict(color=df2['labels'], size=5, line=dict(color=df2['labels'], width=12), opacity=0.8))

data=[trace]
layout=go.Layout(title='Auditory clusters', scene=dict(xaxis=dict(title='AudSD'),
                                             yaxis=dict(title='AudIrreg'),
                                             zaxis=dict(title='AudReg')))
fig=go.Figure(data=data, layout=layout)
py.offline.iplot(fig)
plt.show()

NameError: name 'df1' is not defined

## Saving the result in the form of a csv file with clusters to which each person belong

In [40]:
df2.drop(columns=['Cluster'],inplace=True)

In [41]:
df2.to_csv('C:/Users/zhaleh/PhD_Projects/Hierarchy_to_Beat_Perception_Auditory_Visual/results/Three_Auditory_clusters.csv',index=None)

## Making necessary file for R code to visualize clusters with bars and individual point

In [42]:
df_aud=pd.read_csv('C:/Users/zhaleh/PhD_Projects/Hierarchy_to_Beat_Perception_Auditory_Visual/results/Three_Auditory_clusters.csv')
cluster1aud=df_aud[df_aud['labels']==0].reset_index()
len(cluster1aud)

34

In [43]:
cluster2aud=df_aud[df_aud['labels']==1].reset_index()
len(cluster2aud)

28

In [44]:
cluster3aud=df_aud[df_aud['labels']==2].reset_index()
len(cluster3aud)

39

In [45]:
########################################################## cluster 1
audC1=pd.Series(np.arange(1,len(cluster1aud)*3+1))
for i in range(0,len(cluster1aud)*3):
    if i < len(cluster1aud):
        audC1[i]='Single duration timing'
    elif i < len(cluster1aud)*2:
        audC1[i]='Sequence timing'
    else:
        audC1[i]='Beat-based timing'
dfC1=pd.concat([cluster1aud['AudSD'],cluster1aud['AudSeq'],cluster1aud['AudBeat']],axis=0,ignore_index=True)

dfCluster1=pd.DataFrame({'Timing.level':audC1,'Cluster.1':dfC1})
########################################################## cluster 2
audC2=pd.Series(np.arange(1,len(cluster2aud)*3+1))
for j in range(0,len(cluster2aud)*3):
    if j < len(cluster2aud):
        audC2[j]='Single duration timing'
    elif j < len(cluster2aud)*2:
        audC2[j]='Sequence timing'
    else:
        audC2[j]='Beat-based timing'
dfC2=pd.concat([cluster2aud['AudSD'],cluster2aud['AudSeq'],cluster2aud['AudBeat']],axis=0,ignore_index=True)

dfCluster2=pd.DataFrame({'Timing.level2':audC2,'Cluster.2':dfC2})
########################################################## cluster 3
audC3=pd.Series(np.arange(1,len(cluster3aud)*3+1))
for j in range(0,len(cluster3aud)*3):
    if j < len(cluster3aud):
        audC3[j]='Single duration timing'
    elif j < len(cluster3aud)*2:
        audC3[j]='Sequence timing'
    else:
        audC3[j]='Beat-based timing'
dfC3=pd.concat([cluster3aud['AudSD'],cluster3aud['AudSeq'],cluster3aud['AudBeat']],axis=0,ignore_index=True)

dfCluster3=pd.DataFrame({'Timing.level3':audC3,'Cluster.3':dfC3})
######################################################### Creating the final file 
final=pd.concat([dfCluster1,dfCluster2,dfCluster3],axis=1)
final.to_csv('C:/Users/zhaleh/PhD_Projects/Hierarchy_to_Beat_Perception_Auditory_Visual/results/Three_Auditory_clusters_2.csv',index=None)
